tasks:
  - name: db
    before: cd gitpod
    command: |
      docker-compose up -d
  - name: npm i backend
    before: cd cozero-backend
    command: npm i
  - name: npm i frontend
    before: cd cozero-backend
    command: npm i

github:
  prebuilds:
    branches: true