tasks:
  - name: db
    init: docker-compose up -d
  - name: npm i backend
    before: cd cozero-backend
    init: npm i
  - name: npm i frontend
    before: cd cozero-backend
    init: npm i

github:
  prebuilds:
    branches: true